### ISSUE TITLE
Update Docs about unit testing

### ISSUE THREAD

**Issue by yehezkielgunawan** [yehezkielgunawan/yehez-nexttailwind-starter#52]
In the readme, write the docs how to run the test and write quick explanation about how it works. The unit testing actually has been set, you can check it at `package.json`

**Comment by lauslim12** [comment]
Several minor suggestions from me:

- `jest` can actually provide a unit-test coverage, so we can actually know what is the coverage of our source code.
- `jest` should be verbose so we can actually see the results in-depth.
- While we're talking about unit tests, why don't we also check for circular dependencies with `[dpdm](https://www.npmjs.com/package/dpdm)`? This will help us so we would not fall into a trap of circular dependencies. They are bad for our code.
- What do you think of making two test commands: `test:ci` to be run in GitHub Actions, and `test` to be run locally? `test:ci` will be run in #56 after it is done. In my mind, it could be something like:

```json
"scripts": {
  "test": "jest --watch",
  "test:ci": "jest --ci --collect-coverage --verbose"
}
```

I figured out that I'd probably add these suggestions - but what do you think?

**Comment by yehezkielgunawan** [comment]
@lauslim12 , yes of course you can add it
