### ISSUE TITLE
Setup Simple Workflow

### ISSUE THREAD

**Issue by yehezkielgunawan** [yehezkielgunawan/yehez-nexttailwind-starter#56]
[https://www.youtube.com/watch?v=F3wZTDmHCFA&t=271s](https://www.youtube.com/watch?v=F3wZTDmHCFA&t=271s)

**Comment by lauslim12** [comment]
Hmm, in my mind, there could be several workflows to be run on every pull request.

- Beautify the code with Prettier.
- Check for linter errors with ESLint.
- Check for type errors with TypeScript.
- Run unit tests.

Anything else on your mind?

We may be able to add a workflow for deployment, but I don't think we have/need to set it up; even if it is set up, I'm not sure where should we place it, as you have already integrated Vercel auto deployment into this repository (via webhooks and not with GitHub Actions).

**Comment by yehezkielgunawan** [comment]
Hm... for the deployment I think we keep the existing method (using Webhook) because it's a high-risk task, we'll switch the deployment through Github Action later. At least there's a simple workflow (Github Actions) in this repo @lauslim12 🤣
